version: '3'
services:
  db:
    image: mysql:5.7.30
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/project
      - public-data:/project/public
      - tmp-data:/project/tmp
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PASSWORD: rootpassword
    depends_on:
      - db
    ports:
      - '3000:3000'

volumes:
  mysql_data:
  public-data:
  tmp-data:
